#!/usr/bin/env bash
# Installs Nginx with the following configurations:
#+    Listens on port 80.
#+    Returns a page containing "Hello World!" when queried
#++    at the root with a curl GET request.

sudo apt-get update
sudo apt-get install -y nginx

# Update the default Nginx server block configuration
echo "server {
     listen      80 default_server;
     listen      [::]:80 default_server;
     root        /var/www/html;
     index       index.html index.htm;
}
" | sudo tee /etc/nginx/sites-available/default > /dev/null

# Create the directory and index.html file
sudo mkdir -p /var/www/html
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

# Restart Nginx
sudo service nginx restart

